steps:
  # 1. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/store-repo/main-app:$COMMIT_SHA', '.']
    
  # 2. Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/store-repo/main-app:$COMMIT_SHA']

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'store'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/store-repo/main-app:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--port'
      - '8000'
      - '--set-secrets'
      - 'MONGO_URI=MONGO_URI:latest'
      - '--set-env-vars'
      - 'GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}'

substitutions:
  _GOOGLE_CLIENT_ID: '604130206163-3jk00n1pp845h9m02uf8gbldlbper63g.apps.googleusercontent.com'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/store-repo/main-app:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY